name: Serverless Branch Deployments
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths: # Default to deploying on any change. Change this to limit what triggers branch deployments
      - "**"
env:
  DAGSTER_CLOUD_URL: ${{ secrets.DAGSTER_CLOUD_SERVERLESS_URL }}

jobs:
  check_paths:
    runs-on: ubuntu-20.04
    outputs:
      workspace_changed: ${{ steps.filter.outputs.workspace }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            workspace:
              - "**" # Default to deploying on any change. Change this to limit what triggers branch deployments
  parse_workspace:
    needs: check_paths
    if: needs.check_paths.outputs.workspace_changed == 'true'
    runs-on: ubuntu-latest
    outputs:
      build_info: ${{ steps.parse-workspace.outputs.build_info }}
      secrets_set: ${{ steps.parse-workspace.outputs.secrets_set }}
    steps:
      - uses: actions/checkout@v3
      - name: Parse cloud workspace
        id: parse-workspace
        uses: ./actions/utils/parse_workspace
        with:
          dagster_cloud_file: sample-repo/dagster_cloud.yaml

  dagster_cloud_build_push:
    runs-on: ubuntu-latest
    needs: parse_workspace
    name: Dagster Serverless Branch Deployments
    strategy:
      fail-fast: false
      matrix:
        location: ${{ fromJSON(needs.parse_workspace.outputs.build_info) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.sha }}
      - name: Build and deploy to Dagster Cloud serverless
        uses: ./actions/serverless_branch_deploy
        with:
          dagster_cloud_api_token: ${{ secrets.DAGSTER_CLOUD_SERVERLESS_API_TOKEN }}
          location: ${{ toJson(matrix.location) }}
          env_vars: ${{ toJson(secrets) }}
          base_image: "ghcr.io/dagster-io/dagster-cloud-action:test_custom_base_image"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
